NB_ANGLES = 3
NB_CHANNELS = 1
NB_SLICE = 1
NB_SINGLE_ANGLE = 1

IMAGE_HEIGHT = 155
IMAGE_WIDTH = 135
OUR_MODEL_IMAGE_HEIGHT = 128
OUR_MODEL_IMAGE_WIDTH = 128

ROW_AXIS = 2
COL_AXIS = 3
CHANNEL_AXIS = 4
WIDTH = 155
HEIGHT = 135
RESIZE_DIM = 128
NB_ESTIMATION_TIMESTEPS = NB_PREDICTION_TIMESTEPS = 10
NB_TIMESTEPS = NB_ESTIMATION_TIMESTEPS + NB_PREDICTION_TIMESTEPS
